spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pet_clinic
    username: postgres
    password: 66domama
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  csrf:
    enabled: false
  cors:
    enabled: false